version: '3.7'

services:
  postgres:
    image: postgres:latest
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    
  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  pg_data:

networks:
  default:
    external:
      name: nodejs-network